### ISSUE TITLE
New Website Task List

### ISSUE THREAD

**Issue by terryit3** [terryit3/ppl#1]
- [ ] Figure out why date if imported entries is set to 1970. Has something to do with the way the date is formatted between the old site and new.
- [ ] Verify the job application custom display. Make the entries easier to find.

**Comment by terryit3** [comment]
- [x] Upgraded The Events Calendar Plugin and lost all configuration. Need to setup new venue's and link them from the main menu.

Was able to get config back by reinstalling Events Calendar Pro from backup.
